//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nimap_Company_Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategory
    {
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
    }
}
